# This should be changed once this docker image is made.
image: ubuntu:git

script:
    - apt-get update
    - apt-get install -y nginx docker.io
    - cp nginx/nginx.conf /etc/nginx/nginx.conf
    - nginx
    - service docker start
    - docker build docker/Dockerfile
